### ISSUE TITLE
Enabling prometheus monitoring for PGBouncer

### ISSUE THREAD

**Issue by Skyhikeeper** [icoretech/helm#6]
HI

How do I enable the monitoring of pgbouncer in prometheus using the helm chart, I cannot find the setting to set the monitor option to enable it?

Terence

**Comment by masterkain** [comment]
hello,
usually that's a task for another tool, such as this one:

https://github.com/prometheus-community/pgbouncer_exporter
https://artifacthub.io/packages/helm/prometheus-community/prometheus-pgbouncer-exporter
